-- MySQL Script generated by MySQL Workbench
-- Tue Jul  1 16:59:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_tipo_UNIQUE` (`nome_tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `sobrenome` VARCHAR(250) NOT NULL,
  `id_tipo` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(300) NOT NULL,
  `situacao` TINYINT NOT NULL,
  `data_cadastro` DATETIME NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  INDEX `tipo_idx` (`id_tipo` ASC) VISIBLE,
  CONSTRAINT `tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `mydb`.`usuarios_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`niveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`niveis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_nivel` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `nivel_idx` (`id_nivel` ASC) VISIBLE,
  CONSTRAINT `nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `mydb`.`niveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `curso_idx` (`id_curso` ASC) VISIBLE,
  CONSTRAINT `curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aulas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `observacoes` VARCHAR(45) NULL,
  `data_cadastrada` DATETIME NOT NULL DEFAULT current_timestamp(),
  `id_usuario` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `categorias_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `disciplina_idx` (`id_disciplina` ASC) VISIBLE,
  CONSTRAINT `usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `mydb`.`disciplinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `disciplina_idx` (`id_disciplina` ASC) VISIBLE,
  CONSTRAINT `usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `mydb`.`disciplinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aulas_planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aulas_planos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_aula` INT NOT NULL,
  `id_plano` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `aula_idx` (`id_aula` ASC) VISIBLE,
  INDEX `plano_idx` (`id_plano` ASC) VISIBLE,
  CONSTRAINT `aula`
    FOREIGN KEY (`id_aula`)
    REFERENCES `mydb`.`aulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plano`
    FOREIGN KEY (`id_plano`)
    REFERENCES `mydb`.`planos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_aula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `aula_idx` (`id_aula` ASC) VISIBLE,
  CONSTRAINT `usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aula`
    FOREIGN KEY (`id_aula`)
    REFERENCES `mydb`.`aulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
