-- MySQL Script generated by MySQL Workbench
-- Wed Jul  9 11:21:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bepc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bepc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bepc` DEFAULT CHARACTER SET utf8 ;
USE `bepc` ;

-- -----------------------------------------------------
-- Table `bepc`.`usuarios_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`usuarios_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_tipo_UNIQUE` (`nome_tipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bepc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `sobrenome` VARCHAR(250) NOT NULL,
  `id_tipo` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(300) NOT NULL,
  `situacao` TINYINT NOT NULL,
  `data_cadastro` DATETIME NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  INDEX `tipo_idx` (`id_tipo` ASC),
  CONSTRAINT `tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `bepc`.`usuarios_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bepc`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bepc`.`niveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`niveis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bepc`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_nivel` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `nivel_idx` (`id_nivel` ASC),
  CONSTRAINT `nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `bepc`.`niveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bepc`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`disciplinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `curso_idx` (`id_curso` ASC),
  CONSTRAINT `curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `bepc`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bepc`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`aulas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `observacoes` VARCHAR(45) NULL,
  `data_cadastrada` DATETIME NOT NULL DEFAULT current_timestamp(),
  `id_usuario` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`id_usuario` ASC),
  INDEX `categorias_idx` (`id_categoria` ASC),
  INDEX `disciplina_idx` (`id_disciplina` ASC),
  CONSTRAINT `usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bepc`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `bepc`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `bepc`.`disciplinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bepc`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`planos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`id_usuario` ASC),
  INDEX `disciplina_idx` (`id_disciplina` ASC),
  CONSTRAINT `usuario_fk_planos`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bepc`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disciplina_fk_planos`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `bepc`.`disciplinas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bepc`.`aulas_planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`aulas_planos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_aula` INT NOT NULL,
  `id_plano` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `aula_idx` (`id_aula` ASC),
  INDEX `plano_idx` (`id_plano` ASC),
  CONSTRAINT `aula_fk_aulasplanos`
    FOREIGN KEY (`id_aula`)
    REFERENCES `bepc`.`aulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plano_fk_aulasplanos`
    FOREIGN KEY (`id_plano`)
    REFERENCES `bepc`.`planos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bepc`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bepc`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_aula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`id_usuario` ASC),
  INDEX `aula_idx` (`id_aula` ASC),
  CONSTRAINT `usuario_fk_carrinho`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bepc`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aula_fk_carriho`
    FOREIGN KEY (`id_aula`)
    REFERENCES `bepc`.`aulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bepc`.`usuarios_tipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `bepc`;
INSERT INTO `bepc`.`usuarios_tipo` (`id`, `nome_tipo`) VALUES (1, 'Coordenador');
INSERT INTO `bepc`.`usuarios_tipo` (`id`, `nome_tipo`) VALUES (2, 'Docente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `bepc`.`niveis`
-- -----------------------------------------------------
START TRANSACTION;
USE `bepc`;
INSERT INTO `bepc`.`niveis` (`id`, `nome`) VALUES (1, 'Técnico');
INSERT INTO `bepc`.`niveis` (`id`, `nome`) VALUES (2, 'Livre');
INSERT INTO `bepc`.`niveis` (`id`, `nome`) VALUES (3, 'Graduação');
INSERT INTO `bepc`.`niveis` (`id`, `nome`) VALUES (4, 'Extensão');

COMMIT;

